/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal_admin;

import config.config;
import config.session;
import internal.admin;
import internal.client;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class addAppointmentAd extends javax.swing.JFrame {

    /**
     * Creates new form addAppointment
     */
    public addAppointmentAd() {
        initComponents();
        date();
        displayPets();
    }
    
    private void date(){
        Date date = new Date();
        ap_date.setDateFormatString("MMMM dd, yyyy");
        ap_date.setDate(date);
    }
    
    public void displayPets() {
        config db = new config();
        String sql = "SELECT p_id, owner_id, p_name, p_species, p_breed, p_dateBirth FROM pet";
        db.displayData(sql, petTable);
    }
    public boolean petExists(String petId) {
    try {
        Integer.parseInt(petId);
    } catch (NumberFormatException e) {
        return false; 
    }

    String query = "SELECT COUNT(*) FROM pet WHERE p_id = ?";
    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement(query)) {
        
        pst.setString(1, petId);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            return rs.getInt(1) > 0; 
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return false;
}
    
     public boolean ownerExists(String ownerId) {
    try {
        Integer.parseInt(ownerId);
    } catch (NumberFormatException e) {
        return false; 
    }

    String query = "SELECT COUNT(*) FROM pet WHERE owner_id = ?";
    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement(query)) {
        
        pst.setString(1, ownerId);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            return rs.getInt(1) > 0; 
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return false;
}
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        breed = new javax.swing.JLabel();
        dateBirth = new javax.swing.JLabel();
        ap_reasons = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ap_date = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        ap_pet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        ap_time = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ap_notes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 247, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 219, -1, -1));

        jPanel4.setBackground(new java.awt.Color(214, 206, 160));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Appointment");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        name.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        name.setText("Reasons");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 88, 78, 24));

        breed.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        breed.setText("Date ");
        jPanel1.add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 128, 50, 22));

        dateBirth.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        dateBirth.setText("Time");
        jPanel1.add(dateBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 154, 80, 22));

        ap_reasons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_reasonsActionPerformed(evt);
            }
        });
        jPanel1.add(ap_reasons, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 86, 198, 28));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 158, 118, 28));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel1.setText("Notes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 52, 54, -1));
        jPanel1.add(ap_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 122, 198, 28));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel4.setText("Pet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 56, 32, -1));

        ap_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap_petActionPerformed(evt);
            }
        });
        jPanel1.add(ap_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 50, 198, 28));

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(petTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 218, 576, 244));
        jPanel1.add(ap_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 154, 198, 26));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel6.setText("PETS & OWNER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 186, 192, -1));

        ap_notes.setColumns(20);
        ap_notes.setRows(5);
        jScrollPane3.setViewportView(ap_notes);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 52, 198, 98));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        users u = new users();
        admin admin = new admin(u);
        admin.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void ap_reasonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_reasonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_reasonsActionPerformed

    private void ap_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap_petActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        session sess = session.getInstance();

String apReasons = ap_reasons.getText().trim();
String apPet = ap_pet.getText().trim();
String apTime = ap_time.getText().trim();
String apNotes = ap_notes.getText().trim();

if(apPet.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Pet ID is required.");
    return;
}

java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");

String apDate = "";
if (ap_date.getDate() != null) {
    apDate = sdf.format(ap_date.getDate());
} else {
    JOptionPane.showMessageDialog(this, "Please select a date first!");
    return;
}

if(apReasons.isEmpty() || apTime.isEmpty() || apNotes.isEmpty()){
    JOptionPane.showMessageDialog(this, "Please fill in all fields");
    return;
}

config db = new config();

try (Connection conn = db.connectDB()) {

    // 🔹 Get owner automatically from pet table
    String owner = "";
    String getOwner = "SELECT owner_id FROM pet WHERE p_id = ?";
    PreparedStatement pst = conn.prepareStatement(getOwner);
    pst.setString(1, apPet);

    ResultSet rs = pst.executeQuery();

    if(rs.next()){
        owner = rs.getString("owner_id");

        // optional: display owner in textbox


    }else{
        JOptionPane.showMessageDialog(this,
            "Pet ID [" + apPet + "] does not exist.\nRegister the pet first.");
        ap_pet.requestFocus();
        return;
    }

    // 🔹 Insert appointment
    String sql = "INSERT INTO appointment (ap_petId, ap_clientId, ap_reasons, ap_date, ap_time, ap_notes, ap_status) VALUES (?, ?, ?, ?, ?, ?, ?)";

    PreparedStatement insert = conn.prepareStatement(sql);
    insert.setString(1, apPet);
    insert.setString(2, owner);
    insert.setString(3, apReasons);
    insert.setString(4, apDate);
    insert.setString(5, apTime);
    insert.setString(6, apNotes);
    insert.setString(7, "Pending");

    insert.executeUpdate();

    JOptionPane.showMessageDialog(this, "Appointment Added Successfully!");

    this.dispose();
    users u = new users();
    admin admin = new admin(u);
    admin.setVisible(true);

} catch (Exception e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAppointmentAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAppointmentAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAppointmentAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAppointmentAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAppointmentAd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ap_date;
    private javax.swing.JTextArea ap_notes;
    public javax.swing.JTextField ap_pet;
    private javax.swing.JTextField ap_reasons;
    public javax.swing.JTextField ap_time;
    private javax.swing.JLabel breed;
    private javax.swing.JLabel dateBirth;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel name;
    private javax.swing.JTable petTable;
    // End of variables declaration//GEN-END:variables
}
