/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal_client;

import config.config;
import config.session;
import internal.admin;
import internal.client;
import internal_admin.users;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author James
 */
public class addAppointment extends javax.swing.JFrame {

    /**
     * Creates new form addAppontment
     */

    public addAppointment() {
        initComponents();
        date();
        displayPets();
    }
    
    private void date(){
        Date date = new Date();
        ap_date.setDateFormatString("MMMM dd, yyyy");
        ap_date.setDate(date);
    }
    
    public void displayPets() {
        config db = new config();
        session sess = session.getInstance();
        int userId = sess.getId();

        String sql = "SELECT p_id, p_name, p_species, p_breed, p_dateBirth " +
                     "FROM pet " +
                     "WHERE owner_id = " + userId;

        db.displayData(sql, petTable);
    }
    public boolean petExists(String petId) {
    try {
        Integer.parseInt(petId);
    } catch (NumberFormatException e) {
        return false; 
    }

    String query = "SELECT COUNT(*) FROM pet WHERE p_id = ?";
    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement(query)) {
        
        pst.setString(1, petId);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            return rs.getInt(1) > 0; 
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return false;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        breed = new javax.swing.JLabel();
        dateBirth = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ap_date = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        ap_pet = new javax.swing.JTextField();
        ap_time = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ap_notes = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ap_reasons = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 85, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 219, -1, -1));

        jPanel4.setBackground(new java.awt.Color(47, 62, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 217, 226));
        jLabel2.setText("Appointment");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 13, 163, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, 22, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        name.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(210, 217, 226));
        name.setText("Reasons");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 86, 74, -1));

        breed.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        breed.setForeground(new java.awt.Color(210, 217, 226));
        breed.setText("Date ");
        jPanel1.add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 182, 48, -1));

        dateBirth.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        dateBirth.setForeground(new java.awt.Color(210, 217, 226));
        dateBirth.setText("Time");
        jPanel1.add(dateBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 50, 64, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 217, 226));
        jLabel1.setText("Notes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 82, 54, -1));
        jPanel1.add(ap_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 182, 200, 28));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 217, 226));
        jLabel4.setText("Pet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 52, -1, -1));
        jPanel1.add(ap_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 50, 200, -1));
        jPanel1.add(ap_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 46, 200, 26));

        jPanel3.setBackground(new java.awt.Color(47, 62, 80));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(210, 217, 226));
        jLabel5.setText("Add");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 2, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 182, 88, 28));

        ap_notes.setColumns(20);
        ap_notes.setRows(5);
        jScrollPane2.setViewportView(ap_notes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 80, 200, 96));

        ap_reasons.setColumns(20);
        ap_reasons.setRows(5);
        jScrollPane3.setViewportView(ap_reasons);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 80, 200, 94));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 216));

        jPanel2.setBackground(new java.awt.Color(241, 243, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(petTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 576, 218));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel3.setText("Pet");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 8, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 220, 598, 238));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        session sess = session.getInstance();
String apReasons = ap_reasons.getText().trim();
int apclientId = sess.getId(); // currently logged-in user ID
java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");

// --- Date validation ---
String apDate = "";
if (ap_date.getDate() != null) {
    apDate = sdf.format(ap_date.getDate());
} else {
    JOptionPane.showMessageDialog(this, "Please select a date first!");
    return;
}

// --- Time validation ---
// If using JTextField:
String apTime = ap_time.getText().trim();
// Or, if using JTimeChooser, get the time correctly (see notes below)

String apNotes = ap_notes.getText().trim();
String apPet = ap_pet.getText().trim();

// --- Pet ID validation ---
if(apPet.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Pet ID is required.");
    return;
}

// --- Validate pet exists AND belongs to current user ---
boolean petValid = false;
String checkSql = "SELECT * FROM pet WHERE p_id = ? AND owner_id = ?"; // p_ownerId = client/user ID

try (Connection conn = config.connectDB();
     PreparedStatement pst = conn.prepareStatement(checkSql)) {

    pst.setString(1, apPet);
    pst.setInt(2, apclientId);

    ResultSet rs = pst.executeQuery();
    if(rs.next()){
        petValid = true; // pet exists and belongs to user
    }

} catch(SQLException e){
    e.printStackTrace();
}

if(!petValid){
    JOptionPane.showMessageDialog(this,
        "Pet ID [" + apPet + "] does not exist or does not belong to your account.\n" +
        "Please input a valid ID.",
        "Validation Error",
        JOptionPane.ERROR_MESSAGE);

    ap_pet.setText("");
    ap_pet.requestFocus();
    return;
}

// --- Other fields validation ---
if(apReasons.isEmpty() || apTime.isEmpty() || apNotes.isEmpty()){
    JOptionPane.showMessageDialog(this, "Please fill in all fields");
    return;
}

// --- Insert appointment ---
String sql = "INSERT INTO appointment (ap_petId, ap_clientId, ap_reasons, ap_date, ap_time, ap_notes, ap_status) VALUES (?, ?, ?, ?, ?, ?, ?)";
try (Connection conn = config.connectDB();
     PreparedStatement pst = conn.prepareStatement(sql)) {

    pst.setString(1, apPet);
    pst.setInt(2, apclientId);
    pst.setString(3, apReasons);
    pst.setString(4, apDate);
    pst.setString(5, apTime);
    pst.setString(6, apNotes);
    pst.setString(7, "Pending");

    pst.executeUpdate();
    JOptionPane.showMessageDialog(this, "Appointment Added Successfully!");

} catch(SQLException e){
    e.printStackTrace();
}

// Close form and go back to client dashboard
this.dispose();
client clientForm = new client();
clientForm.setVisible(true);        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
        client client = new client();
        client.setVisible(true);           
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                               if (session.isInstanceEmpty()) {
                JOptionPane.showMessageDialog(null, "Unauthorized. Please log in.");
                new gui.signin().setVisible(true);
                } else {

                    internal_client.account client = new internal_client.account();
                    new client().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ap_date;
    public javax.swing.JTextArea ap_notes;
    public javax.swing.JTextField ap_pet;
    public javax.swing.JTextArea ap_reasons;
    public javax.swing.JTextField ap_time;
    private javax.swing.JLabel breed;
    private javax.swing.JLabel dateBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel name;
    private javax.swing.JTable petTable;
    // End of variables declaration//GEN-END:variables
}
