/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal_client;
import config.config;
import config.session;
import internal.client;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author James
 */
public class updateAppointment extends javax.swing.JFrame {

    /**
     * Creates new form updateAppointment
     */
    public int apId;
    public updateAppointment() {
        initComponents();
        date();
        displayPets();
    }
    private void date(){
        Date date = new Date();
        ap_date.setDateFormatString("MMMM dd, yyyy");
        ap_date.setDate(date);
    }
    
        public void displayPets() {
        config db = new config();
        session sess = session.getInstance();
        String sql = "SELECT p_id, p_name, p_species, p_breed, p_dateBirth " +
                "FROM pet WHERE owner_id =" + sess.getId();
        db.displayData(sql, petTable);
    }
        
        public boolean validateTime(String apTime) {
    if (apTime == null || apTime.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Time cannot be empty");
        return false;
    }
    
   
    String timePattern = "^(0?[1-9]|1[0-2]):[0-5][0-9] (?i)(AM|PM)$";
    
    if (!apTime.matches(timePattern)) {
        JOptionPane.showMessageDialog(this, "Invalid format. Use HH:MM AM/PM (e.g., 9:30 AM)");
        return false;
    }
    
    try {
       
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("h:mm a");
        LocalTime time = LocalTime.parse(apTime.toUpperCase(), formatter);
        
      
        LocalTime startTime = LocalTime.of(8, 0);
        LocalTime endTime = LocalTime.of(17, 0);
        
        LocalTime lunchStart = LocalTime.of(12, 0);
        LocalTime lunchEnd = LocalTime.of(13, 0);
        
        if (time.isBefore(startTime) || time.isAfter(endTime)) {
            JOptionPane.showMessageDialog(this, "Appointments must be between 8:00 AM and 5:00 PM.");
            return false;
        }
        
        if ((time.equals(lunchStart) || time.isAfter(lunchStart)) && time.isBefore(lunchEnd)) {
            JOptionPane.showMessageDialog(this, "The clinic is on lunch break from 12:00 PM to 1:00 PM.");
            return false;
        }
        
        return true; 
        
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Could not parse time. Please check your entry.");
        return false;
    }
}
    
private boolean isTimeSlotConflict(String apDate, String newTimeStr) {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("h:mm a");
    LocalTime newTime;
    try {
        newTime = LocalTime.parse(newTimeStr.toUpperCase(), formatter);
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Invalid time format.");
        return true; 
    }

    LocalTime bufferStart = newTime.minusMinutes(59);
    LocalTime bufferEnd   = newTime.plusMinutes(59);

  
String query = 
    "SELECT ap_time " +
    "FROM appointment " +
    "WHERE ap_date = ? " +
    "  AND ap_id != ? " +
    "  AND ap_status != 'Cancelled'";
    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement(query)) {

        pst.setString(1, apDate);
        pst.setInt(2, this.apId);      

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String existingTimeStr = rs.getString("ap_time");
            try {
                LocalTime existingTime = LocalTime.parse(existingTimeStr.toUpperCase(), formatter);

                if (existingTime.isAfter(bufferStart) && existingTime.isBefore(bufferEnd)) {
                    JOptionPane.showMessageDialog(this,
                        "Conflict: Another appointment exists at " + existingTimeStr +
                        ".\nPlease allow at least 1 hour between appointments.");
                    return true;
                }
            } catch (DateTimeParseException e) {
                continue;
            }
        }

        return false; 

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error checking schedule: " + e.getMessage());
        return true; 
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        breed = new javax.swing.JLabel();
        dateBirth = new javax.swing.JLabel();
        ap_time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ap_date = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        ap_pet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ap_notes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ap_reasons = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 85, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 219, -1, -1));

        jPanel4.setBackground(new java.awt.Color(47, 62, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 217, 226));
        jLabel2.setText("Appointment");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 13, 163, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 9, 22, 28));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        name.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(210, 217, 226));
        name.setText("Reasons");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 88, 74, -1));

        breed.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        breed.setForeground(new java.awt.Color(210, 217, 226));
        breed.setText("Date ");
        jPanel1.add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 182, 48, -1));

        dateBirth.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        dateBirth.setForeground(new java.awt.Color(210, 217, 226));
        dateBirth.setText("Time");
        jPanel1.add(dateBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 52, 76, -1));
        jPanel1.add(ap_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 48, 204, 28));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 217, 226));
        jLabel1.setText("Notes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 84, 54, -1));
        jPanel1.add(ap_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 172, 202, 28));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 217, 226));
        jLabel4.setText("Pet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 52, -1, -1));
        jPanel1.add(ap_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 46, 202, 28));

        ap_notes.setColumns(20);
        ap_notes.setRows(5);
        jScrollPane1.setViewportView(ap_notes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 84, 204, 82));

        ap_reasons.setColumns(20);
        ap_reasons.setRows(5);
        jScrollPane2.setViewportView(ap_reasons);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 84, 202, 82));

        jPanel3.setBackground(new java.awt.Color(47, 62, 80));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(210, 217, 226));
        jLabel6.setText("Save");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 172, 76, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 210));

        jPanel2.setBackground(new java.awt.Color(241, 243, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(petTable);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, 574, 216));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel5.setText("Pets");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 24, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 600, 266));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        client client = new client();
        client.setVisible(true);          
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

        int pid;
try {
    pid = Integer.parseInt(ap_pet.getText().trim());
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid Pet ID. It must be a number.");
    return; 
}       
        String petId = ap_pet.getText().trim();
        if(petId.isEmpty()){
            JOptionPane.showMessageDialog(this, "Pet ID is required.");
            return;
        }
        
        String ar = ap_reasons.getText().trim();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String apDate = ""; 
        if (ap_date.getDate() != null) {
            apDate = sdf.format(ap_date.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "Please select a date first!");
            return; 
        }
        String at = ap_time.getText().trim();
        String an = ap_notes.getText().trim();

        if(ar.isEmpty() || at.isEmpty() || an.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields");
            return;
        }
        if (!validateTime(at)) {
        ap_time.requestFocus(); 
        return; 
    }
if (isTimeSlotConflict(apDate, at)) {
        ap_time.requestFocus();
        return; 
    }

        try (Connection conn = config.connectDB()) {
    
   
    String checkSql = "SELECT COUNT(*) FROM pet WHERE p_id = ?"; 
    PreparedStatement checkPst = conn.prepareStatement(checkSql);
    checkPst.setInt(1, pid);
    ResultSet rs = checkPst.executeQuery();
    
    boolean petExists = false;
    if (rs.next()) {
        petExists = rs.getInt(1) > 0;
    }

    if (!petExists) {
        JOptionPane.showMessageDialog(this,
            "Pet ID [" + pid + "] does not exist.\nPlease input a valid ID.",
            "Validation Error",
            JOptionPane.ERROR_MESSAGE);
        ap_pet.setText("");
        ap_pet.requestFocus();
        return; 
    }

    
    String sql = "UPDATE appointment SET ap_petId=?, ap_reasons=?, ap_date=?, ap_time=?, ap_notes=? WHERE ap_id=?";
    PreparedStatement pst = conn.prepareStatement(sql);
    
    pst.setInt(1, pid);
    pst.setString(2, ar);
    pst.setString(3, apDate);
    pst.setString(4, at);
    pst.setString(5, an);
    pst.setInt(6, apId); 

    int updated = pst.executeUpdate();

    if (updated > 0) {
        JOptionPane.showMessageDialog(this, "Appointment details updated successfully!");
        this.dispose();
        new client().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Update failed! Appointment ID not found.");
    }

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
}
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                                if (session.isInstanceEmpty()) {
                JOptionPane.showMessageDialog(null, "Unauthorized. Please log in.");
                new gui.signin().setVisible(true);
                } else {

                    internal_client.account client = new internal_client.account();
                    new client().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser ap_date;
    public javax.swing.JTextArea ap_notes;
    public javax.swing.JTextField ap_pet;
    public javax.swing.JTextArea ap_reasons;
    public javax.swing.JTextField ap_time;
    private javax.swing.JLabel breed;
    private javax.swing.JLabel dateBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel name;
    private javax.swing.JTable petTable;
    // End of variables declaration//GEN-END:variables
}
