/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal;

import internal_admin.users;

import internal_admin.*;
import config.config;
import config.session;
import gui.signin;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import config.profileImage;
/**
 *
 * @author James
 */

public class admin extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    private users userFrame;


    public admin(users userFrame) {

    initComponents();
    this.userFrame = userFrame;
    displayCurrentUser();

    internal_admin.info info = new internal_admin.info();
    maindesktop.add(info).setVisible(true);

    } 
    Color navcolor = new Color(190,176,112);
    Color bodycolor = new Color(248,247,219);

    public admin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void displayCurrentUser() {

    session sess = session.getInstance();

    if (sess == null) {
        System.out.println("No session found.");
        return;
    }

    config db = new config();

    try (Connection conn = db.connectDB()) {

        String sql = "SELECT * FROM account WHERE a_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, sess.getId());

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            sess.setUsername(rs.getString("a_user"));
            sess.setEmail(rs.getString("a_email"));
            sess.setFname(rs.getString("a_fname"));
            sess.setLname(rs.getString("a_lname"));
            sess.setContact(rs.getString("a_contact"));
            sess.setAddress(rs.getString("a_address"));

            byte[] imgBytes = rs.getBytes("a_image");
            
           

            if (imgBytes != null && imgBytes.length > 0) {

                ImageIcon imageIcon = new ImageIcon(imgBytes);
                Image img = imageIcon.getImage();

                int width = images.getWidth() > 0 ? images.getWidth() : 150;
                int height = images.getHeight() > 0 ? images.getHeight() : 150;

                Image scaledImg = img.getScaledInstance(
                        width,
                        height,
                        Image.SCALE_SMOOTH
                );

                images.setIcon(new ImageIcon(scaledImg));

            } else {
                images.setIcon(null);
            }
                username.setText("<html>"
                    + "<span style='font-size: 12px; font-family: Georgia'><b>Welcome</b></span>, "
                    + "<span style='font-weight: normal; font-size: 10px; font-family: Georgia'>" 
                    + sess.getUsername().trim() 
                    + "</span>"
                    + "</html>");
                    }

    } catch (SQLException e) {
        System.out.println("Error loading account: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        accpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userpane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        images = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        appointpane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        petpane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(190, 176, 112));
        navbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accpane.setBackground(new java.awt.Color(190, 176, 112));
        accpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accpaneMouseExited(evt);
            }
        });
        accpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acc.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        accpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 12, 24, -1));

        jLabel2.setBackground(new java.awt.Color(190, 176, 112));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("  Account");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        accpane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 12, 148, 26));

        navbar.add(accpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 146, 146, 50));

        userpane.setBackground(new java.awt.Color(190, 176, 112));
        userpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpaneMouseExited(evt);
            }
        });
        userpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Users");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        userpane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 16, 146, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        userpane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 10, 28, -1));

        navbar.add(userpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 196, 146, 50));
        navbar.add(images, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 108, 98));

        username.setBackground(new java.awt.Color(0, 0, 0));
        navbar.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 120, 136, 22));

        appointpane.setBackground(new java.awt.Color(190, 176, 112));
        appointpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appointpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appointpaneMouseExited(evt);
            }
        });
        appointpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appoint.png"))); // NOI18N
        appointpane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));

        jLabel9.setBackground(new java.awt.Color(190, 176, 112));
        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("           Appointment");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        appointpane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 14, 146, 26));

        navbar.add(appointpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 246, 146, 50));

        petpane.setBackground(new java.awt.Color(190, 176, 112));
        petpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                petpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                petpaneMouseExited(evt);
            }
        });
        petpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pet.png"))); // NOI18N
        petpane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pets");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        petpane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 124, -1));

        navbar.add(petpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 296, 146, 52));

        jPanel1.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 480));

        jPanel3.setBackground(new java.awt.Color(248, 247, 219));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Admininstrator");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 1, 191, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("—");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 7, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 0, 594, 40));

        maindesktop.setBackground(new java.awt.Color(248, 247, 219));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 590, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        internal_admin.info info = new internal_admin.info();
        maindesktop.add(info).setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setState(ICONIFIED);       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        internal_admin.account profile = new internal_admin.account();
        maindesktop.add(profile).setVisible(true);    
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        accpane.setBackground(bodycolor);   
    }//GEN-LAST:event_jLabel2MouseEntered

    private void accpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseEntered
        accpane.setBackground(bodycolor);      
    }//GEN-LAST:event_accpaneMouseEntered

    private void accpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseExited
        accpane.setBackground(navcolor); 
    }//GEN-LAST:event_accpaneMouseExited

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        accpane.setBackground(navcolor);   
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        internal_admin.users users = new internal_admin.users();
        maindesktop.add(users).setVisible(true);       
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        userpane.setBackground(bodycolor);           
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        userpane.setBackground(navcolor);       
    }//GEN-LAST:event_jLabel5MouseExited

    private void userpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpaneMouseEntered
                    userpane.setBackground(bodycolor);   
    }//GEN-LAST:event_userpaneMouseEntered

    private void userpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpaneMouseExited
                userpane.setBackground(navcolor); 
    }//GEN-LAST:event_userpaneMouseExited

    private void userpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpaneMouseClicked
        internal_admin.users users = new internal_admin.users();
        maindesktop.add(users).setVisible(true);        
    }//GEN-LAST:event_userpaneMouseClicked

    private void accpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseClicked
        internal_admin.account profile = new internal_admin.account();
        maindesktop.add(profile).setVisible(true);         
    }//GEN-LAST:event_accpaneMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        internal_admin.appointment appoint = new internal_admin.appointment();
        maindesktop.add(appoint).setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        appointpane.setBackground(bodycolor);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        appointpane.setBackground(navcolor);
    }//GEN-LAST:event_jLabel9MouseExited

    private void appointpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointpaneMouseClicked
        internal_admin.appointment appoint = new internal_admin.appointment();
        maindesktop.add(appoint).setVisible(true);
    }//GEN-LAST:event_appointpaneMouseClicked

    private void appointpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointpaneMouseEntered
        appointpane.setBackground(bodycolor);
    }//GEN-LAST:event_appointpaneMouseEntered

    private void appointpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointpaneMouseExited
        appointpane.setBackground(navcolor);
    }//GEN-LAST:event_appointpaneMouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        internal_admin.pet pet = new internal_admin.pet();
        maindesktop.add(pet).setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        petpane.setBackground(bodycolor);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        petpane.setBackground(navcolor);
    }//GEN-LAST:event_jLabel11MouseExited

    private void petpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petpaneMouseClicked
        internal_admin.pet pet = new internal_admin.pet();
        maindesktop.add(pet).setVisible(true);
    }//GEN-LAST:event_petpaneMouseClicked

    private void petpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petpaneMouseEntered
        petpane.setBackground(bodycolor);
    }//GEN-LAST:event_petpaneMouseEntered

    private void petpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petpaneMouseExited
        petpane.setBackground(navcolor);
    }//GEN-LAST:event_petpaneMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (session.isInstanceEmpty()) {
                JOptionPane.showMessageDialog(null, "Unauthorized. Please log in.");
                new gui.signin().setVisible(true);
            } else {
                // Only create frames if the user is actually logged in
                internal_admin.users u = new internal_admin.users();
                new admin(u).setVisible(true);
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accpane;
    private javax.swing.JPanel appointpane;
    private javax.swing.JLabel images;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JDesktopPane maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel petpane;
    private javax.swing.JLabel username;
    private javax.swing.JPanel userpane;
    // End of variables declaration//GEN-END:variables
}
