/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal;

import config.config;
import config.session;
import gui.signin;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author James
 */

public class client extends javax.swing.JFrame {

    /**
     * Creates new form clients
     */

    public client() {
        initComponents();
        internal_client.account profile = new internal_client.account();
        maindesktop.add(profile).setVisible(true);
        displayCurrentUser();
    }
    Color navcolor = new Color(21,41,62);
    Color bodycolor = new Color(45, 85, 125);
    
    public void displayCurrentUser() {

    session sess = session.getInstance();

    if (sess == null) {
        System.out.println("No session found.");
        return;
    }

    config db = new config();

    try (Connection conn = db.connectDB()) {

        String sql = "SELECT * FROM account WHERE a_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, sess.getId());

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            sess.setUsername(rs.getString("a_user"));
            sess.setEmail(rs.getString("a_email"));
            sess.setFname(rs.getString("a_fname"));
            sess.setLname(rs.getString("a_lname"));
            sess.setContact(rs.getString("a_contact"));
            sess.setAddress(rs.getString("a_address"));

            byte[] imgBytes = rs.getBytes("a_image");
            
           

            if (imgBytes != null && imgBytes.length > 0) {

                ImageIcon imageIcon = new ImageIcon(imgBytes);
                Image img = imageIcon.getImage();

                int width = images.getWidth() > 0 ? images.getWidth() : 150;
                int height = images.getHeight() > 0 ? images.getHeight() : 150;

                Image scaledImg = img.getScaledInstance(
                        width,
                        height,
                        Image.SCALE_SMOOTH
                );

                images.setIcon(new ImageIcon(scaledImg));

            } else {
                images.setIcon(null);
            }
                username.setText("<html>"
                    + "<span style='font-size: 12px; font-family: Georgia'><b>Welcome</b></span>, "
                    + "<span style='font-weight: normal; font-size: 10px; font-family: Georgia'>" 
                    + sess.getUsername().trim() 
                    + "</span>"
                    + "</html>");
                    }

    } catch (SQLException e) {
        System.out.println("Error loading account: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        appointpane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        petpane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accpane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        outpane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        images1 = new javax.swing.JLabel();
        images = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(21, 41, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appointpane.setBackground(new java.awt.Color(21, 41, 62));
        appointpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appointpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appointpaneMouseExited(evt);
            }
        });
        appointpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whappoint.png"))); // NOI18N
        appointpane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));

        jLabel6.setBackground(new java.awt.Color(190, 176, 112));
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(210, 217, 226));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("           Appointment");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        appointpane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 14, 146, 26));

        jPanel2.add(appointpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 174, 152, 50));

        petpane.setBackground(new java.awt.Color(21, 41, 62));
        petpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                petpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                petpaneMouseExited(evt);
            }
        });
        petpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whpet.png"))); // NOI18N
        petpane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 217, 226));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pets");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        petpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 124, -1));

        jPanel2.add(petpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 152, 52));

        accpane.setBackground(new java.awt.Color(21, 41, 62));
        accpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accpaneMouseExited(evt);
            }
        });
        accpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wh.png"))); // NOI18N
        accpane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));

        jLabel10.setBackground(new java.awt.Color(190, 176, 112));
        jLabel10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(210, 217, 226));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("   Account");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        accpane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 14, 146, 26));

        jPanel2.add(accpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 152, 50));

        outpane.setBackground(new java.awt.Color(21, 41, 62));
        outpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outpaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outpaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                outpaneMouseExited(evt);
            }
        });
        outpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/out.png"))); // NOI18N
        outpane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(210, 217, 226));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sign out ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        outpane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 124, -1));

        jPanel2.add(outpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 428, 146, 52));

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setForeground(new java.awt.Color(210, 217, 226));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 120, 136, 22));

        jPanel3.setBackground(new java.awt.Color(241, 243, 246));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(images1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 114, 98));
        jPanel3.add(images, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 6, 108, 98));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 126, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 480));

        maindesktop.setBackground(new java.awt.Color(241, 243, 246));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 590, 440));

        jPanel7.setBackground(new java.awt.Color(45, 85, 125));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(210, 217, 226));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Client");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 0, 191, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 6, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/miin.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 6, 20, 28));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 590, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
                int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to exit the application?",
        "Confirm Exit",
        JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {
    System.exit(0);
}      
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        internal_client.appointment appointment = new internal_client.appointment();
        maindesktop.add(appointment).setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        appointpane.setBackground(bodycolor);     
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        appointpane.setBackground(navcolor);       
    }//GEN-LAST:event_jLabel6MouseExited

    private void appointpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointpaneMouseEntered
        appointpane.setBackground(bodycolor);      
    }//GEN-LAST:event_appointpaneMouseEntered

    private void appointpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointpaneMouseExited
        appointpane.setBackground(navcolor);     
    }//GEN-LAST:event_appointpaneMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        internal_client.account account = new internal_client.account();
        maindesktop.add(account).setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
            accpane.setBackground(bodycolor);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
            accpane.setBackground(navcolor);
    }//GEN-LAST:event_jLabel10MouseExited

    private void accpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseEntered
            accpane.setBackground(bodycolor);
    }//GEN-LAST:event_accpaneMouseEntered

    private void accpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseExited
            accpane.setBackground(navcolor);
    }//GEN-LAST:event_accpaneMouseExited

    private void petpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petpaneMouseEntered
        petpane.setBackground(bodycolor);   
    }//GEN-LAST:event_petpaneMouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        petpane.setBackground(bodycolor);    
    }//GEN-LAST:event_jLabel1MouseEntered

    private void petpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petpaneMouseExited
        petpane.setBackground(navcolor);       
    }//GEN-LAST:event_petpaneMouseExited

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        petpane.setBackground(navcolor);        
    }//GEN-LAST:event_jLabel1MouseExited

    private void petpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petpaneMouseClicked
        internal_client.pet pet = new internal_client.pet();
        maindesktop.add(pet).setVisible(true);
    }//GEN-LAST:event_petpaneMouseClicked
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        internal_client.pet pet = new internal_client.pet();
        maindesktop.add(pet).setVisible(true);                
    }//GEN-LAST:event_jLabel1MouseClicked

    private void appointpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointpaneMouseClicked
        internal_client.appointment appointment = new internal_client.appointment();
        maindesktop.add(appointment).setVisible(true);      
    }//GEN-LAST:event_appointpaneMouseClicked

    private void accpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accpaneMouseClicked
        internal_client.account account = new internal_client.account();
        maindesktop.add(account).setVisible(true);    
    }//GEN-LAST:event_accpaneMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();
        new signin().setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        outpane.setBackground(bodycolor);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        outpane.setBackground(navcolor);
    }//GEN-LAST:event_jLabel12MouseExited

    private void outpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outpaneMouseClicked
        this.dispose();
        new signin().setVisible(true);
    }//GEN-LAST:event_outpaneMouseClicked

    private void outpaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outpaneMouseEntered
        outpane.setBackground(bodycolor);
    }//GEN-LAST:event_outpaneMouseEntered

    private void outpaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outpaneMouseExited
        outpane.setBackground(navcolor);
    }//GEN-LAST:event_outpaneMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (session.isInstanceEmpty()) {
                JOptionPane.showMessageDialog(null, "Unauthorized. Please log in.");
                new gui.signin().setVisible(true);
                } else {

                    internal_client.account client = new internal_client.account();
                    new client().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accpane;
    private javax.swing.JPanel appointpane;
    private javax.swing.JLabel images;
    private javax.swing.JLabel images1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JDesktopPane maindesktop;
    private javax.swing.JPanel outpane;
    private javax.swing.JPanel petpane;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
